## Data Wrangling

- It is a process of gathering, collecting and transforming raw data into another form for better analysis, better understanding, better decision making, accessing in less time. Data Wrangling is also known as Data Munging.
- Data Wrangling in simple terms just means that cleaning the data to get better insights out of the available.

## Data Wrangling Python libraries

1. Pandas - Data Cleaning and Data Transformation library
2. NumPy - Numerical Analysis like array etc
3. Matplotlib : Data Visualization
4. seaborn : Data Visualization
5. sklearn : Machine Learning 

## How to install all the libraries listed above 

- Syntax : !pip install [library_name]

In [3]:
## Install pandas library

!pip install pandas

Error processing line 3 of C:\Users\AMANT\anaconda3\lib\site-packages\googleapis_common_protos-1.56.4-py3.10-nspkg.pth:

  Traceback (most recent call last):
    File "C:\Users\AMANT\anaconda3\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 562, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored


In [4]:
## Install numpy libarary

!pip install numpy

Error processing line 3 of C:\Users\AMANT\anaconda3\lib\site-packages\googleapis_common_protos-1.56.4-py3.10-nspkg.pth:

  Traceback (most recent call last):
    File "C:\Users\AMANT\anaconda3\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 562, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored


In [5]:
## Check the already installed libraries

!pip list

Package                       Version
----------------------------- ---------------
absl-py                       1.4.0
alabaster                     0.7.12
anaconda-client               1.11.1
anaconda-navigator            2.4.0
and                           66.0.2
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
array-record                  0.2.0
arrow                         1.2.3
astroid                       2.14.2
astropy                       5.1
asttokens                     2.0.5
astunparse                    1.6.3
atomicwrites                  1.4.0
attrs                         22.1.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.11.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.0
beautif

Error processing line 3 of C:\Users\AMANT\anaconda3\lib\site-packages\googleapis_common_protos-1.56.4-py3.10-nspkg.pth:

  Traceback (most recent call last):
    File "C:\Users\AMANT\anaconda3\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 562, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored


## You installed a completely new library and you want to check the version

In [6]:
## Install seaborn library

!pip install seaborn 

Error processing line 3 of C:\Users\AMANT\anaconda3\lib\site-packages\googleapis_common_protos-1.56.4-py3.10-nspkg.pth:

  Traceback (most recent call last):
    File "C:\Users\AMANT\anaconda3\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 562, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored


In [7]:
## Print the version of the library

import seaborn 
seaborn.__version__

'0.12.2'

## Update a library
- Syntax : conda update --all (all the libraries will be updated)
- This syntax can be used only in anaconda prompt

## How to use a library in jupyter notebook

In [1]:
ls = [10, 20, 30, 40]
ls

[10, 20, 30, 40]

In [2]:
numpy.array(ls)

NameError: name 'numpy' is not defined

In [9]:
## I want to use numpy library to create a numpy array

import numpy
numpy.array(ls)

array([10, 20, 30, 40])

In [10]:
numpy.ones([10])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
numpy.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
## Provide an alias name to the libraries

import numpy as np
np.array(ls)

array([10, 20, 30, 40])

In [13]:
np.ones([10])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Alias names for all the DW libraries

In [16]:
## Common standard alias names used across Data Science community

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
import numpy as num

In [20]:
num.array(ls)

array([10, 20, 30, 40])

## Process of DataWrangling

- Explore Data to get the understanding of the data
- Deal with missing values in the data
- Reshape the data
- Filter the data based out of some condition
- Sorting from most popular to least popular (highest to lowest)
- Combining the data set from multiple different sources
- Reducing the data size by removing the unwanted columns or rows from the data.
- Others

## NumPy Library:

- NumPy - Numerical Python
- Mainly used for only numerical analysis
- NumPy arrays are the core building block of the NumPy library

In [21]:
ls

[10, 20, 30, 40]

In [24]:
type(ls)

list

In [23]:
## 

import numpy as np
arr = np.array(ls)
arr

array([10, 20, 30, 40])

In [25]:
type(arr)

numpy.ndarray

## Why do we need a NumPy array when both array and a list look similar
Ans : NumPy arrays are faster in processing compared to a Python list

In [26]:
import numpy as np
import time
import sys

In [35]:
## Create 2 Python lists
l1 = range(10000)
l2 = range(10000)

In [34]:
## Create 2 NumPy arrays
a1 = np.arange(10000)
a2 = np.arange(10000)

In [36]:
## Add the values of the list by keeping track of time before and after addition

start = time.time()
result = [(x + y) for x, y in zip(l1, l2)]
print("python list takes : ", (time.time() - start) * 1000)

python list takes :  1.5175342559814453


In [37]:
## Add the values of the arrays by keeping track of time before and after addition

start = time.time()
result = a1 + a2
print("NumPy array takes : ", (time.time() - start) * 1000)

NumPy array takes :  1.0004043579101562


- NumPy arrays are faster than Python list by 0.5 sec in this example in real time there will be huge difference in time.
- Hence, NumPy arrays are faster in processing compared to Python lists

## Drawbacks of NumPy arrays

In [38]:
l1 = [10, 20.57, 'Red', 45, 56.78, 'Sam']
l1

[10, 20.57, 'Red', 45, 56.78, 'Sam']

In [39]:
np.array(l1)

array(['10', '20.57', 'Red', '45', '56.78', 'Sam'], dtype='<U32')

In [ ]:
# list : 10 is an int, 20.57 is a float, 'Red' is a string
# array : '10' is string, '20.57' is also a string, 'Red' is also a string